// <auto-generated />
using System;
using DBPractise.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBPractise.Migrations
{
    [DbContext(typeof(DbOsiedleContext))]
    [Migration("20200112165429_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBPractise.Models.Blok", b =>
                {
                    b.Property<int>("IdBlk")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_bloku")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Id_osiedla")
                        .HasColumnType("int");

                    b.Property<int>("NrBloku")
                        .HasColumnName("Numer_bloku")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnName("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Zarobki")
                        .HasColumnName("Zarobki")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdBlk");

                    b.HasIndex("Id_osiedla");

                    b.ToTable("Blok");

                    b.HasData(
                        new
                        {
                            IdBlk = 1,
                            NrBloku = 1,
                            Ulica = "Siemianowicka",
                            Zarobki = 46715m
                        },
                        new
                        {
                            IdBlk = 2,
                            NrBloku = 2,
                            Ulica = "Balonowa",
                            Zarobki = 57673m
                        },
                        new
                        {
                            IdBlk = 3,
                            NrBloku = 3,
                            Ulica = "Wiedźmińska",
                            Zarobki = 14975m
                        },
                        new
                        {
                            IdBlk = 4,
                            NrBloku = 4,
                            Ulica = "Dworcowa",
                            Zarobki = 4036m
                        },
                        new
                        {
                            IdBlk = 5,
                            NrBloku = 5,
                            Ulica = "Garbarska",
                            Zarobki = 44008m
                        });
                });

            modelBuilder.Entity("DBPractise.Models.BlokParking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdBlok")
                        .HasColumnType("int");

                    b.Property<int>("IdParking")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdBlok");

                    b.HasIndex("IdParking");

                    b.ToTable("Blok_Parking");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdBlok = 1,
                            IdParking = 1
                        },
                        new
                        {
                            Id = 2,
                            IdBlok = 2,
                            IdParking = 2
                        },
                        new
                        {
                            Id = 3,
                            IdBlok = 3,
                            IdParking = 3
                        },
                        new
                        {
                            Id = 4,
                            IdBlok = 4,
                            IdParking = 4
                        },
                        new
                        {
                            Id = 5,
                            IdBlok = 5,
                            IdParking = 5
                        });
                });

            modelBuilder.Entity("DBPractise.Models.Osiedle", b =>
                {
                    b.Property<int>("Id_os")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_osiedla")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Id_zarządcy")
                        .HasColumnType("int");

                    b.Property<int>("Lb_Mieszk")
                        .HasColumnName("Liczba_mieszkańców")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa_os")
                        .IsRequired()
                        .HasColumnName("Nazwa_osiedla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_os");

                    b.HasIndex("Id_zarządcy");

                    b.ToTable("Osiedle");

                    b.HasData(
                        new
                        {
                            Id_os = 1,
                            Lb_Mieszk = 10984,
                            Nazwa_os = "Wojkowice"
                        },
                        new
                        {
                            Id_os = 2,
                            Lb_Mieszk = 4402,
                            Nazwa_os = "Wojkowice"
                        },
                        new
                        {
                            Id_os = 3,
                            Lb_Mieszk = 5889,
                            Nazwa_os = "Szombierki"
                        },
                        new
                        {
                            Id_os = 4,
                            Lb_Mieszk = 9304,
                            Nazwa_os = "Batorego"
                        },
                        new
                        {
                            Id_os = 5,
                            Lb_Mieszk = 5280,
                            Nazwa_os = "Witosa"
                        });
                });

            modelBuilder.Entity("DBPractise.Models.Parking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_parkingu")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Lb_Miejsc_Dla_Inw")
                        .HasColumnName("Ilosc_Miejsc_Dla_Inwalidow")
                        .HasColumnType("int");

                    b.Property<int>("Lb_Miejsc_Nie_Przypis")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("[Ilosc_Miejsc_Parkingowych]-[Ilosc_Przypisanych_Miejsc]");

                    b.Property<int>("Lb_Miejsc_Park")
                        .HasColumnName("Ilosc_Miejsc_Parkingowych")
                        .HasColumnType("int");

                    b.Property<int>("Lb_Przypis_Miejsc")
                        .HasColumnName("Ilosc_Przypisanych_Miejsc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Parking");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lb_Miejsc_Dla_Inw = 2,
                            Lb_Miejsc_Nie_Przypis = 0,
                            Lb_Miejsc_Park = 25,
                            Lb_Przypis_Miejsc = 10
                        },
                        new
                        {
                            Id = 2,
                            Lb_Miejsc_Dla_Inw = 4,
                            Lb_Miejsc_Nie_Przypis = 0,
                            Lb_Miejsc_Park = 56,
                            Lb_Przypis_Miejsc = 7
                        },
                        new
                        {
                            Id = 3,
                            Lb_Miejsc_Dla_Inw = 3,
                            Lb_Miejsc_Nie_Przypis = 0,
                            Lb_Miejsc_Park = 92,
                            Lb_Przypis_Miejsc = 15
                        },
                        new
                        {
                            Id = 4,
                            Lb_Miejsc_Dla_Inw = 4,
                            Lb_Miejsc_Nie_Przypis = 0,
                            Lb_Miejsc_Park = 99,
                            Lb_Przypis_Miejsc = 54
                        },
                        new
                        {
                            Id = 5,
                            Lb_Miejsc_Dla_Inw = 3,
                            Lb_Miejsc_Nie_Przypis = 0,
                            Lb_Miejsc_Park = 34,
                            Lb_Przypis_Miejsc = 22
                        });
                });

            modelBuilder.Entity("DBPractise.Models.Zarzadca", b =>
                {
                    b.Property<int>("IdZarzadcy")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_zarządcy")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Id_osiedla")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnName("Imię")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnName("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Zarobki")
                        .HasColumnName("Zarobki")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdZarzadcy");

                    b.HasIndex("Id_osiedla");

                    b.ToTable("Zarządca");

                    b.HasData(
                        new
                        {
                            IdZarzadcy = 1,
                            Imie = "Zygmunt",
                            Nazwisko = "Kowal",
                            Zarobki = 6940m
                        },
                        new
                        {
                            IdZarzadcy = 2,
                            Imie = "Władysław",
                            Nazwisko = "Kowal",
                            Zarobki = 14850m
                        },
                        new
                        {
                            IdZarzadcy = 3,
                            Imie = "Wilhelm",
                            Nazwisko = "Jabłkowski",
                            Zarobki = 14520m
                        },
                        new
                        {
                            IdZarzadcy = 4,
                            Imie = "Krystyna",
                            Nazwisko = "Warius",
                            Zarobki = 4750m
                        },
                        new
                        {
                            IdZarzadcy = 5,
                            Imie = "Krystyna",
                            Nazwisko = "Fikus",
                            Zarobki = 9710m
                        });
                });

            modelBuilder.Entity("DBPractise.Models.Blok", b =>
                {
                    b.HasOne("DBPractise.Models.Osiedle", "Osiedle")
                        .WithMany()
                        .HasForeignKey("Id_osiedla");
                });

            modelBuilder.Entity("DBPractise.Models.BlokParking", b =>
                {
                    b.HasOne("DBPractise.Models.Blok", "Blok")
                        .WithMany("BlokiParkingi")
                        .HasForeignKey("IdBlok")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBPractise.Models.Parking", "Parking")
                        .WithMany("BlokiParkingi")
                        .HasForeignKey("IdParking")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBPractise.Models.Osiedle", b =>
                {
                    b.HasOne("DBPractise.Models.Zarzadca", "Zarzadca")
                        .WithMany()
                        .HasForeignKey("Id_zarządcy");
                });

            modelBuilder.Entity("DBPractise.Models.Zarzadca", b =>
                {
                    b.HasOne("DBPractise.Models.Osiedle", "Osiedle")
                        .WithMany()
                        .HasForeignKey("Id_osiedla");
                });
#pragma warning restore 612, 618
        }
    }
}
